import 'package:collection/collection.dart';

/// Roles that can be assigned to a guided navigation object.
///
/// See https://readium.org/guided-navigation/schema/roles.schema.json
enum GuidedNavigationRole {
  abstract('abstract'),
  acknowledgments('acknowledgments'),
  afterword('afterword'),
  appendix('appendix'),
  article('article'),
  aside('aside'),
  audio('audio'),
  backlink('backlink'),
  bibliography('bibliography'),
  biblioref('biblioref'),
  blockquote('blockquote'),
  body('body'),
  caption('caption'),
  chapter('chapter'),
  cell('cell'),
  columnheader('columnheader'),
  colophon('colophon'),
  complementary('complementary'),
  conclusion('conclusion'),
  cover('cover'),
  credit('credit'),
  credits('credits'),
  dedication('dedication'),
  definition('definition'),
  details('details'),
  endnotes('endnotes'),
  epigraph('epigraph'),
  epilogue('epilogue'),
  errata('errata'),
  example('example'),
  figure('figure'),
  footnote('footnote'),
  foreword('foreword'),
  glossary('glossary'),
  glossref('glossref'),
  header('header'),
  heading1('heading1'),
  heading2('heading2'),
  heading3('heading3'),
  heading4('heading4'),
  heading5('heading5'),
  heading6('heading6'),
  image('image'),
  // Renamed from `index` to avoid conflict with the built-in Enum.index property.
  documentIndex('index'),
  introduction('introduction'),
  landmarks('landmarks'),
  list('list'),
  listItem('listItem'),
  loa('loa'),
  loi('loi'),
  lot('lot'),
  lov('lov'),
  main('main'),
  math('math'),
  navigation('navigation'),
  noteref('noteref'),
  notice('notice'),
  pagebreak('pagebreak'),
  pagelist('pagelist'),
  paragraph('paragraph'),
  part('part'),
  preface('preface'),
  preformatted('preformatted'),
  presentation('presentation'),
  prologue('prologue'),
  pullquote('pullquote'),
  qna('qna'),
  region('region'),
  row('row'),
  rowheader('rowheader'),
  section('section'),
  separator('separator'),
  sequence('sequence'),
  subtitle('subtitle'),
  summary('summary'),
  table('table'),
  term('term'),
  tip('tip'),
  toc('toc'),
  video('video');

  const GuidedNavigationRole(this.value);
  final String value;

  static GuidedNavigationRole? optFromString(String? value) =>
      GuidedNavigationRole.values.firstWhereOrNull((r) => r.value == value);
}
