name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          channel: stable
          flutter-version: '3.41.9'

      - name: Install dependencies (platform interface)
        run: flutter pub get
        working-directory: flutter_readium_platform_interface

      - name: Test platform interface
        run: flutter test --coverage
        working-directory: flutter_readium_platform_interface

      - name: Install dependencies (flutter_readium)
        run: flutter pub get
        working-directory: flutter_readium

      - name: Test flutter_readium
        run: flutter test --coverage
        working-directory: flutter_readium

      - name: Upload coverage
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
        with:
          files: |
            flutter_readium_platform_interface/coverage/lcov.info
            flutter_readium/coverage/lcov.info
          fail_ci_if_error: false
